# Generated by Django 5.2.9 on 2025-12-11 13:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lectures', '0002_alter_grade_passed'),
        ('organization', '0001_initial'),
        ('persons', '0005_alter_student_course_alter_student_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Titel')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='Problemstellung')),
                ('goal', models.TextField(blank=True, null=True, verbose_name='Zielsetzung')),
                ('methodology', models.TextField(blank=True, null=True, verbose_name='Methodik')),
                ('approved_oper', models.BooleanField(db_column='approved_oper', default=False, verbose_name='Vom Betrieb genehmigt')),
                ('approved_scien', models.BooleanField(db_column='approved_scien', default=False, verbose_name='Von wiss. Betreuung genehmigt')),
                ('approved_orga', models.BooleanField(db_column='approved_orga', default=False, verbose_name='Von Studiengangsleitung genehmigt')),
                ('topic_submitted_date', models.DateField(blank=True, db_column='topic_submitted_date', null=True, verbose_name='Thema eingereicht am')),
                ('start_date', models.DateField(db_column='start_date', verbose_name='Startdatum')),
                ('end_date', models.DateField(db_column='end_date', verbose_name='Abgabefrist')),
                ('company_context', models.CharField(blank=True, db_column='company_context', max_length=200, null=True, verbose_name='Firma des Unternehmensbetreuers')),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200, null=True, verbose_name='Kommentar (z.B. Betreuerwunsch)')),
                ('assessor_oper', models.ForeignKey(blank=True, db_column='assessor_oper_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researches_oper', to='persons.person', verbose_name='Betreuung (betrieblich)')),
                ('assessor_scien', models.ForeignKey(blank=True, db_column='assessor_scien_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='researches_acad', to='persons.personnel', verbose_name='Betreuung (wissenschaftlich)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='persons.student', verbose_name='Student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='researches', to='lectures.moduleunit', verbose_name='Lehrveranstaltung')),
            ],
            options={
                'verbose_name': 'Forschungsarbeit',
                'verbose_name_plural': 'Forschungsarbeiten',
                'db_table': 'researches',
                'ordering': ['-start_date'],
                'unique_together': {('student', 'unit', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='ResearchAssessorWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Anzahl möglicher Betreuungen')),
                ('max_count_orga', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Anzahl Vergabe laut Orga')),
                ('random_sel', models.BooleanField(default=False, help_text='Sollen Studenten zufällig zugewiesen werden?', verbose_name='Zufällige Auswahl')),
                ('comment', models.TextField(verbose_name='Kommentar')),
                ('submitted_date', models.DateField(verbose_name='Eingereicht am')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_wishes', to='organization.studyyear', verbose_name='Jahrgang')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_wishes', to='persons.personnel', verbose_name='Betreuer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessor_wishes', to='lectures.moduleunit', verbose_name='Lehrveranstaltung')),
            ],
            options={
                'verbose_name': 'Betreuerwunsch',
                'verbose_name_plural': 'Betreuerwünsche',
                'db_table': 'research_assessorwish',
                'ordering': ['academic_year', 'personnel'],
                'unique_together': {('personnel', 'unit', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ResearchMatchWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(blank=True, help_text='5 = höchste Priorität', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Priorität')),
                ('person_from', models.ForeignKey(db_column='person_from_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_wishes_made', to='persons.person', verbose_name='Von (Person)')),
                ('personnel_who', models.ForeignKey(db_column='personnel_who_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_wishes_received', to='persons.personnel', verbose_name='Gewünschter Betreuer')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_wishes', to='researches.research', verbose_name='Forschungsarbeit')),
            ],
            options={
                'verbose_name': 'Matching-Wunsch',
                'verbose_name_plural': 'Matching-Wünsche',
                'db_table': 'research_matchwish',
                'ordering': ['research', 'priority'],
                'unique_together': {('research', 'person_from', 'personnel_who')},
            },
        ),
    ]
