# Generated by Django 5.2.9 on 2025-12-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAcademy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(max_length=30, verbose_name='Akademiename')),
            ],
            options={
                'verbose_name': 'Akademie',
                'verbose_name_plural': 'Akademien',
                'db_table': 'study_academies',
                'ordering': ['academy_name'],
            },
        ),
        migrations.CreateModel(
            name='StudyOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organisationsname')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'db_table': 'study_organisation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_progr', models.CharField(max_length=50, verbose_name='Studiengang')),
            ],
            options={
                'verbose_name': 'Studiengang',
                'verbose_name_plural': 'Studiengänge',
                'db_table': 'study_study',
                'ordering': ['study_progr'],
            },
        ),
        migrations.CreateModel(
            name='StudySemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_short', models.CharField(max_length=20, verbose_name='Kurzname')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('type', models.CharField(choices=[('Praxis', 'Praxisphase'), ('Theorie', 'Theoriephase')], max_length=10, verbose_name='Typ')),
                ('cycle', models.CharField(choices=[('A', 'A-Zyklus'), ('B', 'B-Zyklus'), ('X', 'Unabhängig')], max_length=1, verbose_name='Zyklus')),
                ('special', models.CharField(blank=True, choices=[('First', 'Erstes Semester'), ('Last', 'Letztes Semester')], max_length=5, null=True, verbose_name='Besonderheit')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
                'db_table': 'study_semester',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyfield', models.CharField(max_length=30, verbose_name='Studienrichtung')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='organization.studyprogram', verbose_name='Studiengang')),
            ],
            options={
                'verbose_name': 'Studienrichtung',
                'verbose_name_plural': 'Studienrichtungen',
                'db_table': 'study_field',
                'ordering': ['study', 'studyfield'],
            },
        ),
        migrations.CreateModel(
            name='StudyYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_name', models.CharField(max_length=20, verbose_name='Jahrgangsbezeichnung')),
                ('semester_id1p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_1p', to='organization.studysemester', verbose_name='1. Semester Praxis')),
                ('semester_id1t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_1t', to='organization.studysemester', verbose_name='1. Semester Theorie')),
                ('semester_id2p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_2p', to='organization.studysemester', verbose_name='2. Semester Praxis')),
                ('semester_id2t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_2t', to='organization.studysemester', verbose_name='2. Semester Theorie')),
                ('semester_id3p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_3p', to='organization.studysemester', verbose_name='3. Semester Praxis')),
                ('semester_id3t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_3t', to='organization.studysemester', verbose_name='3. Semester Theorie')),
                ('semester_id4p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_4p', to='organization.studysemester', verbose_name='4. Semester Praxis')),
                ('semester_id4t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_4t', to='organization.studysemester', verbose_name='4. Semester Theorie')),
                ('semester_id5p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_5p', to='organization.studysemester', verbose_name='5. Semester Praxis')),
                ('semester_id5t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_5t', to='organization.studysemester', verbose_name='5. Semester Theorie')),
                ('semester_id6p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_6p', to='organization.studysemester', verbose_name='6. Semester Praxis')),
                ('semester_id6t', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='year_6t', to='organization.studysemester', verbose_name='6. Semester Theorie')),
            ],
            options={
                'verbose_name': 'Studienjahr',
                'verbose_name_plural': 'Studienjahre',
                'db_table': 'study_year',
                'ordering': ['-year_name'],
            },
        ),
        migrations.CreateModel(
            name='StudyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_nr', models.CharField(max_length=20, verbose_name='Kursnummer')),
                ('academy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.studyacademy', verbose_name='Akademie')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.studyfield', verbose_name='Studienrichtung')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.studyorganisation', verbose_name='Organisation')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organization.studyyear', verbose_name='Jahrgang')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'db_table': 'study_courses',
                'ordering': ['course_nr'],
            },
        ),
    ]
