# Generated by Django 5.2.9 on 2025-12-11 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('persons', '0005_alter_student_course_alter_student_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_nr', models.CharField(max_length=30, unique=True, verbose_name='Modulnummer')),
                ('name', models.CharField(max_length=200, verbose_name='Modulname')),
                ('credits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ECTS Credits')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='organization.studyfield', verbose_name='Studienrichtung')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='organization.studyprogram', verbose_name='Studiengang')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Module',
                'db_table': 'modules',
                'ordering': ['module_nr'],
            },
        ),
        migrations.CreateModel(
            name='ModuleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_nr', models.CharField(max_length=15, verbose_name='Veranstaltungsnummer')),
                ('unit_name', models.CharField(max_length=200, verbose_name='Veranstaltungsname')),
                ('unit_name_short', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kurzname')),
                ('units', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lehreinheiten')),
                ('semester_nr', models.IntegerField(help_text='Semester in dem die Veranstaltung stattfindet (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Semester-Nr')),
                ('module', models.ForeignKey(db_column='ModuleNr', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='lectures.module', to_field='module_nr', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Lehrveranstaltung',
                'verbose_name_plural': 'Lehrveranstaltungen',
                'db_table': 'module_units',
                'ordering': ['module', 'semester_nr', 'unit_nr'],
                'unique_together': {('module', 'unit_nr')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField(default=1, help_text='Prüfungsversuch (1-3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)], verbose_name='Versuch')),
                ('passed', models.BooleanField(default=True, verbose_name='Bestanden')),
                ('grade', models.DecimalField(decimal_places=1, help_text='Note von 1.0 bis 5.0', max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='persons.student', verbose_name='Student')),
                ('module', models.ForeignKey(db_column='ModuleNr', on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='lectures.module', to_field='module_nr', verbose_name='Modul')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='lectures.moduleunit', verbose_name='Lehrveranstaltung')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Noten',
                'db_table': 'grades',
                'ordering': ['student', 'module'],
                'indexes': [models.Index(fields=['student', 'module'], name='grades_student_815ec5_idx')],
                'unique_together': {('student', 'module', 'attempt')},
            },
        ),
    ]
