# Generated by Django 5.2.9 on 2025-12-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='passed',
            field=models.BooleanField(db_column='Passed', default=True, verbose_name='Bestanden'),
        ),
    ]
