# Generated by Django 5.2.9 on 2025-12-10 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Titel')),
                ('firstname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Geburtstag')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Männlich'), ('F', 'Weiblich'), ('D', 'Divers')], max_length=1, null=True, verbose_name='Geschlecht')),
                ('salutation_short', models.CharField(blank=True, max_length=50, null=True, verbose_name='Anrede (kurz)')),
                ('salutation_full', models.CharField(blank=True, max_length=150, null=True, verbose_name='Anrede (voll)')),
                ('mail_main', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Haupt-E-Mail')),
                ('tel_main', models.CharField(blank=True, max_length=30, null=True, verbose_name='Haupt-Telefon')),
                ('role_now', models.CharField(choices=[('ST', 'Student'), ('MA', 'Mitarbeiter'), ('DOZ', 'Dozent'), ('CO', 'Company'), ('COAS', 'Company Assessor'), ('TEST', 'Test')], max_length=10, verbose_name='Aktuelle Rolle')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
                'db_table': 'persons',
                'ordering': ['lastname', 'firstname'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_nr', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Personalnummer')),
                ('actant_type', models.IntegerField(help_text='Typ des Aktanten (z.B. Dozent, Verwaltung, etc.)', verbose_name='Aktantentyp')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_profile', to='persons.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personnel',
                'ordering': ['personnel_nr'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matri_nr', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Matrikelnummer')),
                ('course_id', models.IntegerField(blank=True, null=True, verbose_name='Kurs ID')),
                ('field_id', models.IntegerField(blank=True, null=True, verbose_name='Feld ID')),
                ('company_id', models.IntegerField(blank=True, null=True, verbose_name='Unternehmen ID')),
                ('company_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_students', to='persons.person', verbose_name='Ansprechpartner im Unternehmen')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='persons.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Studenten',
                'db_table': 'students',
                'ordering': ['matri_nr'],
            },
        ),
    ]
