# Generated by Django 5.2.9 on 2025-12-10 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_nr', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Unternehmensnummer')),
                ('adressform', models.CharField(help_text='z.B. Herrn, Frau, Firma', max_length=300, verbose_name='Adressform')),
                ('name', models.CharField(max_length=300, verbose_name='Unternehmensname')),
                ('street', models.CharField(blank=True, max_length=400, null=True, verbose_name='Straße')),
                ('district', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bezirk/Ortsteil')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stadt')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bundesland')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Land')),
                ('tel_main', models.CharField(blank=True, max_length=200, null=True, verbose_name='Haupt-Telefon')),
                ('mail_main', models.EmailField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Haupt-E-Mail')),
                ('mail_person', models.EmailField(blank=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Ansprechpartner-E-Mail')),
                ('webpage', models.URLField(blank=True, max_length=300, null=True, verbose_name='Webseite')),
            ],
            options={
                'verbose_name': 'Unternehmen',
                'verbose_name_plural': 'Unternehmen',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='company_id',
        ),
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='persons.company', verbose_name='Unternehmen'),
            preserve_default=False,
        ),
    ]
