# Generated by Django 5.2.9 on 2025-12-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('persons', '0002_company_remove_student_company_id_student_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='field_id',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.studycourse', verbose_name='Kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.studyfield', verbose_name='Studienrichtung'),
            preserve_default=False,
        ),
    ]
