# Generated by Django 5.2.9 on 2025-12-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_remove_student_course_id_remove_student_field_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='persons.company', verbose_name='Unternehmen'),
        ),
    ]
