# Generated by Django 5.2.9 on 2025-12-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('persons', '0004_alter_student_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organization.studycourse', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organization.studyfield', verbose_name='Studienrichtung'),
        ),
    ]
