# Generated by Django 5.2.9 on 2026-02-24 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('persons', '0005_alter_student_course_alter_student_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer-Account'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='organisations',
            field=models.ManyToManyField(blank=True, related_name='personnel', to='organization.studyorganisation', verbose_name='Studiengangsorganisationen'),
        ),
    ]
