# Generated by Django 5.2.9 on 2026-02-24 12:53

from django.db import migrations

GROUP_NAMES = ['student', 'employee', 'lecturer', 'mentor', 'supervisor']


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for name in GROUP_NAMES:
        Group.objects.get_or_create(name=name)


def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=GROUP_NAMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_add_user_field_and_organisations'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=remove_groups),
    ]
