"""
Django settings for sgverwaltung project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['sync.heilbronn.dhbw.de', 'localhost', '127.0.0.1', '193.197.8.50']
CSRF_TRUSTED_ORIGINS = ['http://sync.heilbronn.dhbw.de', 'https://sync.heilbronn.dhbw.de']
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djangosaml2',
    'accounts',
    'persons',
    'organization',
    'lectures',
    'researches',
    'imports'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'djangosaml2.middleware.SamlSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.AccessCheckMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sgverwaltung.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.utils.utils_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'sgverwaltung.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_ALL_TABLES'",
        }
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": config('REDIS_URL', default='redis://127.0.0.1:6379'),
    }
}

AUTHENTICATION_BACKENDS = [
    'djangosaml2.backends.Saml2Backend',
    'django.contrib.auth.backends.ModelBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'static_collected'

STATICFILES_DIRS = [
    (BASE_DIR / 'static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

######## SAML2 Konfiguration
import saml2

SAML_CONFIG = {
    'xmlsec_binary': config('XMLSEC_BINARY', default='/usr/bin/xmlsec1'),
    'entityid': 'https://sync.heilbronn.dhbw.de/saml2/metadata/',

    'service': {
        'sp': {
            'name': 'SYNC',

            'endpoints': {
                'assertion_consumer_service': [
                    ('https://sync.heilbronn.dhbw.de/saml2/acs/',
                     saml2.BINDING_HTTP_POST),
                ],
                'single_logout_service': [
                    ('https://sync.heilbronn.dhbw.de/saml2/ls/',
                     saml2.BINDING_HTTP_REDIRECT),
                ],
            },

            # Attribute Mapping
            'required_attributes': ['mail'],
            'optional_attributes': ['uid', 'givenName', 'sn', 'eduPersonAffiliation', 'eduPersonScopedAffiliation'],

            'allow_unsolicited': True,
            'want_assertions_signed': True,
            'want_response_signed': False,
        },
    },

    'metadata': {
        'remote': [
            {
                'url': 'https://idp.heilbronn.dhbw.de/idp/shibboleth',
            },
        ],
    },

    'key_file': str(BASE_DIR / 'saml_certs/saml-sp-key.pem'),
    'cert_file': str(BASE_DIR / 'saml_certs/saml-sp-cert.pem'),

    'encryption_keypairs': [
        {
            'key_file': str(BASE_DIR / 'saml_certs/saml-sp-key.pem'),
            'cert_file': str(BASE_DIR / 'saml_certs/saml-sp-cert.pem'),
        }
    ],

    'accepted_time_diff': 120,
}

# Attribute Mapping
SAML_ATTRIBUTE_MAPPING = {
    'mail': ('username', 'email'),  # mail als primärer identifier
    'givenName': ('first_name',),
    'sn': ('last_name',),
    'uid': ('username',),  # überschreibt mail wenn uid später verfügbar
}

SAML_CSP_HANDLER = ''

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/django.log',
            'formatter': 'verbose',
        },
        'file_sgverwaltung': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/sgverwaltung.log',
            'formatter': 'verbose',
        },
        'file_mail': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs/mail.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
        'saml2': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
        'djangosaml2': {
            'handlers': ['console'],
            'level': 'ERROR',
        },
        'sgverwaltung.email': {
            'handlers': ['file_mail'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'sgverwaltung.auth': {
            'handlers': ['file_sgverwaltung', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# E-Mail-Konfiguration
EMAIL_BACKEND       = config('EMAIL_BACKEND',       default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST          = config('EMAIL_HOST',           default='localhost')
EMAIL_PORT          = config('EMAIL_PORT',           default=587, cast=int)
EMAIL_USE_TLS       = config('EMAIL_USE_TLS',        default=True,  cast=bool)
EMAIL_USE_SSL       = config('EMAIL_USE_SSL',        default=False, cast=bool)
EMAIL_HOST_USER     = config('EMAIL_HOST_USER',      default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD',  default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL',   default='SYNC <noreply@heilbronn.dhbw.de>')

# Wenn DEBUG=True, werden alle E-Mails an diese Adresse umgeleitet.
DEBUG_EMAIL_RECIPIENT = config('DEBUG_EMAIL_RECIPIENT', default='dev@example.com')

# Bei Sendefehlern erhält diese Adresse eine Benachrichtigung.
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@example.com')


# URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True